fix: backport kubevirt tcpdump improvements to release-1.16
Signed-off-by: zhangzujian <zhangzujian.7@gmail.com>

diff --git a/dist/images/kubectl-ko b/dist/images/kubectl-ko
--- a/dist/images/kubectl-ko
+++ b/dist/images/kubectl-ko
@@ -147,48 +147,87 @@ ipIsInCidr(){
 }
 
 tcpdump(){
-  namespacedPod="$1"; shift
+  local namespacedPod="$1"; shift
+  local namespace podName vmName nodeName isVm=false
   namespace=$(echo "$namespacedPod" | cut -d "/" -f1)
   podName=$(echo "$namespacedPod" | cut -d "/" -f2)
   if [ "$podName" = "$namespacedPod" ]; then
-    namespace="default"
+    namespace=$(kubectl config view --minify -o jsonpath='{..namespace}')
+    namespace=${namespace:-default}
   fi
 
-  nodeName=$(kubectl get pod "$podName" -n "$namespace" -o jsonpath={.spec.nodeName})
+  # --ignore-not-found makes an absent VMI a normal Pod case while still
+  # returning errors such as RBAC failures to the caller.
+  local vmiOwner
+  vmiOwner=$(kubectl get vmi "$podName" -n "$namespace" --ignore-not-found -o jsonpath='{.metadata.ownerReferences[?(@.kind == "VirtualMachine")].kind}')
+  if [ "$vmiOwner" = "VirtualMachine" ]; then
+    isVm=true
+    vmName="$podName"
+
+    local sourcePod targetPod
+    sourcePod=$(kubectl get vmi "$vmName" -n "$namespace" -o jsonpath='{.status.migrationState.sourcePod}')
+    targetPod=$(kubectl get vmi "$vmName" -n "$namespace" -o jsonpath='{.status.migrationState.targetPod}')
+    if [ -n "$sourcePod" ] && [ -z "$targetPod" ]; then
+      podName="$sourcePod"
+      echo "WARNING: Migration in progress; capturing source Pod $podName" >&2
+    elif [ -n "$targetPod" ]; then
+      podName="$targetPod"
+    else
+      nodeName=$(kubectl get vmi "$vmName" -n "$namespace" -o jsonpath='{.status.nodeName}')
+      podName=$(kubectl get pod -n "$namespace" -l vm.kubevirt.io/name="$vmName" \
+        --field-selector="spec.nodeName=$nodeName,status.phase=Running" \
+        -o jsonpath='{.items[0].metadata.name}')
+    fi
+  fi
+
+  local podOwner
+  podOwner=$(kubectl get pod "$podName" -n "$namespace" --ignore-not-found -o jsonpath='{.metadata.ownerReferences[?(@.kind == "VirtualMachineInstance")].kind}')
+  if [ "$podOwner" = "VirtualMachineInstance" ]; then
+    vmName=$(kubectl get pod "$podName" -n "$namespace" -o jsonpath='{.metadata.ownerReferences[?(@.kind == "VirtualMachineInstance")].name}')
+    isVm=true
+  fi
+
+  nodeName=$(kubectl get pod "$podName" -n "$namespace" -o jsonpath='{.spec.nodeName}')
   hostNetwork=$(kubectl get pod "$podName" -n "$namespace" -o jsonpath={.spec.hostNetwork})
 
   if [ -z "$nodeName" ]; then
-    echo "Pod $namespacedPod not exists on any node"
+    echo "Pod $namespacedPod not exists on any node" >&2
     exit 1
   fi
 
-  ovsPod=$(kubectl get pod -n $KUBE_OVN_NS -l app=ovs -o 'jsonpath={.items[?(@.spec.nodeName=="'$nodeName'")].metadata.name}')
+  local ovsPod
+  ovsPod=$(kubectl get pod -n "$KUBE_OVN_NS" -l app=ovs -o 'jsonpath={.items[?(@.spec.nodeName=="'$nodeName'")].metadata.name}')
   if [ -z "$ovsPod" ]; then
-    echo "ovs-ovn not exist on node $nodeName"
+    echo "ovs-ovn not exist on node $nodeName" >&2
     exit 1
   fi
 
   if [ "$hostNetwork" = "true" ]; then
     set -x
-    kubectl exec "$ovsPod" -n $KUBE_OVN_NS -- tcpdump -nn "$@"
+    kubectl exec "$ovsPod" -n "$KUBE_OVN_NS" -c openvswitch -- tcpdump -nn "$@"
   else
-    nicName=$(kubectl exec "$ovsPod" -n $KUBE_OVN_NS -- ovs-vsctl --data=bare --no-heading --columns=name find interface external-ids:iface-id="$podName"."$namespace" | tr -d '\r')
+    local nicName podNicType podNetNs ovnCni
+    local ifaceOwner="$podName"
+    if [ "$isVm" = "true" ]; then
+      ifaceOwner="$vmName"
+    fi
+    nicName=$(kubectl exec "$ovsPod" -n "$KUBE_OVN_NS" -c openvswitch -- ovs-vsctl --data=bare --no-heading --columns=name find interface external-ids:iface-id="$ifaceOwner"."$namespace" | tr -d '\r')
     if [ -z "$nicName" ]; then
-      echo "nic doesn't exist on node $nodeName"
+      echo "nic doesn't exist on node $nodeName" >&2
       exit 1
     fi
     podNicType=$(kubectl get pod "$podName" -n "$namespace" -o jsonpath={.metadata.annotations.ovn\\.kubernetes\\.io/pod_nic_type})
-    podNetNs=$(kubectl exec "$ovsPod" -n $KUBE_OVN_NS -- ovs-vsctl --data=bare --no-heading get interface "$nicName" external-ids:pod_netns | tr -d '\r' | sed -e 's/^"//' -e 's/"$//')
-    ovnCni=$(kubectl get pod -n $KUBE_OVN_NS -l app=kube-ovn-cni -o 'jsonpath={.items[?(@.spec.nodeName=="'$nodeName'")].metadata.name}')
+    podNetNs=$(kubectl exec "$ovsPod" -n "$KUBE_OVN_NS" -c openvswitch -- ovs-vsctl --data=bare --no-heading get interface "$nicName" external-ids:pod_netns | tr -d '\r' | sed -e 's/^"//' -e 's/"$//')
+    ovnCni=$(kubectl get pod -n "$KUBE_OVN_NS" -l app=kube-ovn-cni -o 'jsonpath={.items[?(@.spec.nodeName=="'$nodeName'")].metadata.name}')
     if [ -z "$ovnCni" ]; then
-      echo "kube-ovn-cni not exist on node $nodeName"
+      echo "kube-ovn-cni not exist on node $nodeName" >&2
       exit 1
     fi
     set -x
     if [ "$podNicType" = "internal-port" ]; then
-      kubectl exec "$ovnCni" -n $KUBE_OVN_NS -- nsenter --net="$podNetNs" tcpdump -nn -i "$nicName" "$@"
+      kubectl exec "$ovnCni" -n "$KUBE_OVN_NS" -c cni-server -- nsenter --net="$podNetNs" tcpdump -nn -i "$nicName" "$@"
     else
-      kubectl exec "$ovnCni" -n $KUBE_OVN_NS -- nsenter --net="$podNetNs" tcpdump -nn -i eth0 "$@"
+      kubectl exec "$ovnCni" -n "$KUBE_OVN_NS" -c cni-server -- nsenter --net="$podNetNs" tcpdump -nn -i eth0 "$@"
     fi
   fi
 }
