fix: kube-proxy check

diff --git a/dist/images/kubectl-ko b/dist/images/kubectl-ko
--- a/dist/images/kubectl-ko
+++ b/dist/images/kubectl-ko
@@ -156,6 +156,7 @@ xxctl(){
 }
 
 diagnose(){
+  kubectl get crd vpcs.kubeovn.io
   kubectl get crd subnets.kubeovn.io
   kubectl get crd ips.kubeovn.io
   kubectl get svc kube-dns -n kube-system
@@ -268,11 +269,21 @@ checkDeployment(){
 }
 
 checkKubeProxy(){
-  healthResult=`kubectl get node -o wide | grep -v "INTERNAL-IP" | awk '{printf "curl -g -6 -sL -w %{http_code} http://[%s]:10256/healthz -o /dev/null | grep -v 200 \n", $6}' | bash` || true
-  if [ -n "$healthResult" ]; then
-    echo "kube-proxy's health check failed"
-    exit 1
+  dsMode=`kubectl get ds -n kube-system | grep kube-proxy || true`
+  if [ -z "$dsMode" ]; then
+    nodeIps=`kubectl get node -o wide | grep -v "INTERNAL-IP" | awk '{print $6}'`
+    for node in $nodeIps
+    do
+      healthResult=`curl -g -6 -sL -w %{http_code} http://[$node]:10256/healthz -o /dev/null | grep -v 200 || true`
+      if [ -n "$healthResult" ]; then
+        echo "$node kube-proxy's health check failed"
+        exit 1
+      fi
+    done
+  else
+    checkDaemonSet kube-proxy
   fi
+  echo "kube-proxy ready"
 }
 
 if [ $# -lt 1 ]; then
